"""Mix two generated sphere packings in a 3 x 3 x 6 um periodic box.

The script reads the real-unit CSV files generated by SpherePackGen, keeps all
particle radii, randomly mixes the two species, and re-packs them with a
rectangular-box adaptation of the project's force_biased dense-packing method.

Run from the repository root:

    python scripts/mix_generated_structures_force_biased.py

Use --dry-run to only inspect the imported particle counts and target volume
fraction without generating a new packing.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np


DEFAULT_INPUT_150 = Path("results/monodisperse_150nm_phi050_3um/particles_real_units.csv")
DEFAULT_INPUT_200 = Path("results/monodisperse_200nm_phi050_3um/particles_real_units.csv")
DEFAULT_OUTPUT = Path("results/mixed_150nm_200nm_3x3x6um_force_biased")
NOMINAL_DENSITY_RATIO = 1.2
DEFAULT_OUTER_DIAMETER_RATIO = NOMINAL_DENSITY_RATIO ** (1.0 / 3.0)


@dataclass
class ParticleInput:
    radii: np.ndarray
    species_id: np.ndarray
    source_id: np.ndarray
    source_name: str


@dataclass
class ValidationReport:
    passed: bool
    errors: list[str]
    warnings: list[str]
    metrics: dict[str, float | int | list[float]]


def _json_ready(value):
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(k): _json_ready(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_ready(v) for v in value]
    return value


def load_real_unit_csv(path: Path, *, species_id: int, source_id: int, source_name: str) -> ParticleInput:
    radii: list[float] = []
    with path.open("r", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames or "radius" not in reader.fieldnames:
            raise ValueError(f"{path} must contain a 'radius' column.")
        for row in reader:
            radius = float(row["radius"])
            if not math.isfinite(radius) or radius <= 0.0:
                raise ValueError(f"{path} contains an invalid radius: {row['radius']!r}")
            radii.append(radius)
    if not radii:
        raise ValueError(f"{path} contains no particles.")
    n = len(radii)
    return ParticleInput(
        radii=np.asarray(radii, dtype=float),
        species_id=np.full(n, int(species_id), dtype=np.int32),
        source_id=np.full(n, int(source_id), dtype=np.int32),
        source_name=source_name,
    )


class RectPeriodicCellList:
    """Periodic cell list for an orthorhombic box."""

    def __init__(self, box_lengths: np.ndarray, cutoff: float):
        self.box_lengths = np.asarray(box_lengths, dtype=float)
        self.cutoff = max(float(cutoff), 1.0e-12)
        self.n_cells = np.maximum(1, np.floor(self.box_lengths / self.cutoff).astype(int))
        self.cell_size = self.box_lengths / self.n_cells
        self.cells: dict[tuple[int, int, int], list[int]] = defaultdict(list)

    def _cell_index(self, position: np.ndarray) -> tuple[int, int, int]:
        wrapped = np.mod(position, self.box_lengths)
        idx = np.floor(wrapped / self.cell_size).astype(int)
        idx = np.mod(idx, self.n_cells)
        return int(idx[0]), int(idx[1]), int(idx[2])

    def build(self, positions: np.ndarray):
        self.cells.clear()
        for i, pos in enumerate(positions):
            self.cells[self._cell_index(pos)].append(int(i))

    def add(self, index: int, position: np.ndarray):
        self.cells[self._cell_index(position)].append(int(index))

    def nearby_indices(self, position: np.ndarray, search_radius: float):
        span = np.maximum(1, np.ceil(float(search_radius) / self.cell_size).astype(int))
        base = self._cell_index(position)
        seen: set[int] = set()
        for dx in range(-int(span[0]), int(span[0]) + 1):
            for dy in range(-int(span[1]), int(span[1]) + 1):
                for dz in range(-int(span[2]), int(span[2]) + 1):
                    cell = (
                        (base[0] + dx) % int(self.n_cells[0]),
                        (base[1] + dy) % int(self.n_cells[1]),
                        (base[2] + dz) % int(self.n_cells[2]),
                    )
                    for idx in self.cells.get(cell, []):
                        if idx not in seen:
                            seen.add(idx)
                            yield idx


def minimum_image_delta(a: np.ndarray, b: np.ndarray, box_lengths: np.ndarray) -> np.ndarray:
    diff = np.asarray(a, dtype=float) - np.asarray(b, dtype=float)
    return diff - box_lengths * np.rint(diff / box_lengths)


def pair_gap(position_i, radius_i, position_j, radius_j, box_lengths: np.ndarray) -> float:
    delta = minimum_image_delta(position_i, position_j, box_lengths)
    return float(np.linalg.norm(delta) - radius_i - radius_j)


def _candidate_min_gap_rect(
    candidate: np.ndarray,
    radius: float,
    positions: np.ndarray,
    radii: np.ndarray,
    cell_list: RectPeriodicCellList,
    box_lengths: np.ndarray,
    max_radius: float,
) -> float:
    min_gap = float("inf")
    for j in cell_list.nearby_indices(candidate, radius + max_radius):
        gap = pair_gap(candidate, radius, positions[j], radii[j], box_lengths)
        if gap < min_gap:
            min_gap = gap
            if min_gap < 0.0:
                break
    return min_gap


def poisson_disk_place_rect(
    radii: np.ndarray,
    box_lengths: np.ndarray,
    rng: np.random.Generator,
    *,
    max_attempts_per_particle: int,
    candidates_per_particle: int,
    progress_every: int = 1000,
):
    """Place reduced-radius spheres with best-candidate sampling."""
    radii = np.asarray(radii, dtype=float)
    order = np.argsort(-radii)
    sorted_radii = radii[order]
    positions_sorted = np.empty((len(radii), 3), dtype=float)
    max_radius = float(np.max(sorted_radii))
    cell_list = RectPeriodicCellList(box_lengths, cutoff=max(2.0 * max_radius, 1.0e-12))
    total_attempts = 0
    valid_candidate_count = 0
    accepted = 0

    for local_idx, radius in enumerate(sorted_radii):
        if accepted == 0:
            positions_sorted[local_idx] = rng.random(3) * box_lengths
            cell_list.add(local_idx, positions_sorted[local_idx])
            accepted += 1
            continue

        best_candidate = None
        best_gap = -np.inf
        attempts_for_particle = 0
        batch_size = max(1, int(candidates_per_particle))
        while attempts_for_particle < max_attempts_per_particle:
            current_batch = min(batch_size, max_attempts_per_particle - attempts_for_particle)
            candidates = rng.random((current_batch, 3)) * box_lengths
            attempts_for_particle += current_batch
            total_attempts += current_batch
            for candidate in candidates:
                gap = _candidate_min_gap_rect(
                    candidate,
                    float(radius),
                    positions_sorted,
                    sorted_radii,
                    cell_list,
                    box_lengths,
                    max_radius,
                )
                if gap >= 0.0:
                    valid_candidate_count += 1
                    if gap > best_gap:
                        best_gap = gap
                        best_candidate = candidate
            if best_candidate is not None:
                break

        if best_candidate is None:
            raise RuntimeError(
                f"Initial reduced-radius placement failed after {max_attempts_per_particle} "
                f"attempts for particle {local_idx}."
            )
        positions_sorted[local_idx] = best_candidate
        cell_list.add(local_idx, best_candidate)
        accepted += 1
        if progress_every and accepted % progress_every == 0:
            print(f"initial placement: accepted {accepted}/{len(radii)}")

    positions = np.empty_like(positions_sorted)
    positions[order] = positions_sorted
    return positions, {
        "total_attempts": int(total_attempts),
        "valid_candidate_count": int(valid_candidate_count),
        "accepted": int(accepted),
        "candidates_per_particle": int(candidates_per_particle),
        "candidate_strategy": "rectangular_periodic_best_candidate",
    }


class VerletPairCacheRect:
    def __init__(self, radii: np.ndarray, box_lengths: np.ndarray, outer_ratio_cutoff: float, skin: float):
        self.radii = np.asarray(radii, dtype=float)
        self.box_lengths = np.asarray(box_lengths, dtype=float)
        self.outer_ratio_cutoff = float(outer_ratio_cutoff)
        self.skin = max(float(skin), 1.0e-12)
        self.reference_positions: np.ndarray | None = None
        self.pair_i = np.empty(0, dtype=np.int64)
        self.pair_j = np.empty(0, dtype=np.int64)
        self.rebuild_count = 0
        self.max_displacement_since_rebuild = 0.0

    def ensure_current(self, positions: np.ndarray):
        if self.reference_positions is None:
            self._rebuild(positions)
            return
        deltas = positions - self.reference_positions
        deltas -= self.box_lengths * np.rint(deltas / self.box_lengths)
        max_displacement = float(np.max(np.linalg.norm(deltas, axis=1))) if len(deltas) else 0.0
        self.max_displacement_since_rebuild = max_displacement
        if max_displacement > 0.5 * self.skin:
            self._rebuild(positions)

    def _rebuild(self, positions: np.ndarray):
        pair_i: list[int] = []
        pair_j: list[int] = []
        n = len(self.radii)
        if n >= 2:
            max_radius = float(np.max(self.radii))
            cell_cutoff = max(2.0 * self.outer_ratio_cutoff * max_radius + self.skin, 1.0e-12)
            cell_list = RectPeriodicCellList(self.box_lengths, cutoff=cell_cutoff)
            cell_list.build(positions)
            for i in range(n):
                search_radius = self.outer_ratio_cutoff * (self.radii[i] + max_radius) + self.skin
                for j in cell_list.nearby_indices(positions[i], search_radius):
                    if j <= i:
                        continue
                    delta = minimum_image_delta(positions[i], positions[j], self.box_lengths)
                    dist = float(np.linalg.norm(delta))
                    cutoff = self.outer_ratio_cutoff * (self.radii[i] + self.radii[j]) + self.skin
                    if dist <= cutoff:
                        pair_i.append(i)
                        pair_j.append(j)

        self.pair_i = np.asarray(pair_i, dtype=np.int64)
        self.pair_j = np.asarray(pair_j, dtype=np.int64)
        self.reference_positions = positions.copy()
        self.rebuild_count += 1
        self.max_displacement_since_rebuild = 0.0


def _outer_shell_forces_rect(
    positions: np.ndarray,
    radii: np.ndarray,
    box_lengths: np.ndarray,
    outer_ratio: float,
    rng: np.random.Generator,
    pair_cache: VerletPairCacheRect,
):
    forces = np.zeros_like(positions)
    pair_cache.ensure_current(positions)
    pair_i = pair_cache.pair_i
    pair_j = pair_cache.pair_j
    candidate_pair_count = int(len(pair_i))
    if candidate_pair_count == 0:
        return forces, {
            "max_shell_overlap": 0.0,
            "shell_overlap_count": 0,
            "shell_overlap_sum": 0.0,
            "max_overlap": 0.0,
            "overlap_count": 0,
            "overlap_sum": 0.0,
            "inner_diameter_ratio": float("inf"),
            "candidate_pair_count": 0,
        }

    deltas = positions[pair_i] - positions[pair_j]
    deltas -= box_lengths * np.rint(deltas / box_lengths)
    distances = np.linalg.norm(deltas, axis=1)
    true_contacts = radii[pair_i] + radii[pair_j]
    valid = true_contacts > 0.0
    inner_ratio = float(np.min(distances[valid] / true_contacts[valid])) if np.any(valid) else float("inf")

    shell_overlaps = outer_ratio * true_contacts - distances
    shell_active = shell_overlaps > 0.0
    shell_overlap_count = int(np.count_nonzero(shell_active))
    shell_overlap_sum = float(np.sum(shell_overlaps[shell_active])) if shell_overlap_count else 0.0
    max_shell_overlap = float(np.max(shell_overlaps[shell_active])) if shell_overlap_count else 0.0

    true_overlaps = true_contacts - distances
    overlap_active = true_overlaps > 0.0
    overlap_count = int(np.count_nonzero(overlap_active))
    overlap_sum = float(np.sum(true_overlaps[overlap_active])) if overlap_count else 0.0
    max_overlap = float(np.max(true_overlaps[overlap_active])) if overlap_count else 0.0

    if shell_overlap_count:
        active_i = pair_i[shell_active]
        active_j = pair_j[shell_active]
        active_deltas = deltas[shell_active]
        active_distances = distances[shell_active]
        directions = np.zeros_like(active_deltas)
        nonzero = active_distances > 1.0e-12
        directions[nonzero] = active_deltas[nonzero] / active_distances[nonzero, None]
        if np.any(~nonzero):
            random_directions = rng.normal(size=(int(np.count_nonzero(~nonzero)), 3))
            norms = np.linalg.norm(random_directions, axis=1)
            bad = norms <= 1.0e-12
            if np.any(bad):
                random_directions[bad] = np.array([1.0, 0.0, 0.0])
                norms[bad] = 1.0
            directions[~nonzero] = random_directions / norms[:, None]
        pair_forces = shell_overlaps[shell_active, None] * directions
        np.add.at(forces, active_i, pair_forces)
        np.add.at(forces, active_j, -pair_forces)

    return forces, {
        "max_shell_overlap": float(max_shell_overlap),
        "shell_overlap_count": int(shell_overlap_count),
        "shell_overlap_sum": float(shell_overlap_sum),
        "max_overlap": float(max_overlap),
        "overlap_count": int(overlap_count),
        "overlap_sum": float(overlap_sum),
        "inner_diameter_ratio": float(inner_ratio),
        "candidate_pair_count": candidate_pair_count,
    }


def packing_fraction(radii: np.ndarray, box_lengths: np.ndarray) -> float:
    return float(np.sum(4.0 * np.pi * radii**3 / 3.0) / float(np.prod(box_lengths)))


def _updated_outer_ratio(
    *,
    outer_ratio: float,
    initial_outer_ratio: float,
    inner_ratio: float,
    active_phi: float,
    contraction_rate: float,
) -> float:
    if not np.isfinite(inner_ratio):
        return 1.0
    inner_porosity = 1.0 - active_phi * inner_ratio**3
    nominal_porosity = 1.0 - active_phi * NOMINAL_DENSITY_RATIO
    difference = inner_porosity - nominal_porosity
    if difference <= 0.0:
        return float(outer_ratio)
    j = float(np.ceil(-np.log10(max(difference, 1.0e-300))))
    decrement = (0.5**j) * float(initial_outer_ratio) * float(contraction_rate)
    return max(1.0, float(outer_ratio) - decrement)


def force_biased_relax_rect(
    positions: np.ndarray,
    radii: np.ndarray,
    box_lengths: np.ndarray,
    rng: np.random.Generator,
    *,
    max_iterations: int,
    initial_outer_ratio: float,
    contraction_rate: float,
    force_scaling_factor: float,
    max_displacement_fraction: float,
    tolerance_overlap: float,
    verlet_skin: float,
):
    outer_ratio = float(initial_outer_ratio)
    active_phi = packing_fraction(radii, box_lengths)
    diameters = np.maximum(2.0 * radii, 1.0e-12)
    max_displacement = np.maximum(float(max_displacement_fraction) * radii, 1.0e-12)
    pair_cache = VerletPairCacheRect(radii, box_lengths, outer_ratio, verlet_skin)
    forces, last_diag = _outer_shell_forces_rect(positions, radii, box_lengths, outer_ratio, rng, pair_cache)

    iterations = 0
    stop_reason = "max_iterations"
    for _ in range(max_iterations):
        inner_ratio = float(last_diag["inner_diameter_ratio"])
        if last_diag["shell_overlap_count"] == 0:
            stop_reason = "no_outer_shell_contacts"
            break
        if outer_ratio <= inner_ratio and last_diag["max_overlap"] <= tolerance_overlap:
            stop_reason = "outer_ratio_reached_inner_ratio"
            break
        if outer_ratio <= 1.0 + 1.0e-12 and last_diag["max_overlap"] <= tolerance_overlap:
            stop_reason = "true_non_overlap_reached"
            break

        displacement = (
            float(force_scaling_factor)
            * outer_ratio**2
            * forces
            / (2.0 * diameters[:, None])
        )
        norms = np.linalg.norm(displacement, axis=1)
        too_large = norms > max_displacement
        if np.any(too_large):
            displacement[too_large] *= (max_displacement[too_large] / norms[too_large])[:, None]

        positions = np.mod(positions + displacement, box_lengths)
        iterations += 1
        forces, last_diag = _outer_shell_forces_rect(positions, radii, box_lengths, outer_ratio, rng, pair_cache)
        outer_ratio = _updated_outer_ratio(
            outer_ratio=outer_ratio,
            initial_outer_ratio=initial_outer_ratio,
            inner_ratio=float(last_diag["inner_diameter_ratio"]),
            active_phi=active_phi,
            contraction_rate=contraction_rate,
        )

    return positions, {
        "iterations_used": int(iterations),
        "max_iterations": int(max_iterations),
        "outer_diameter_ratio_final": float(outer_ratio),
        "packing_fraction_active": float(active_phi),
        "stop_reason": stop_reason,
        "verlet_skin": float(verlet_skin),
        "pair_cache_rebuilds": int(pair_cache.rebuild_count),
        **last_diag,
    }


def generate_force_biased_rect(
    radii: np.ndarray,
    box_lengths: np.ndarray,
    rng: np.random.Generator,
    args: argparse.Namespace,
):
    start = time.perf_counter()
    initial_fraction = float(args.initial_radius_fraction)
    if not 0.0 < initial_fraction <= 1.0:
        raise ValueError("--initial-radius-fraction must be in (0, 1].")
    if int(args.stages) < 1:
        raise ValueError("--stages must be >= 1.")

    start_radii = radii * initial_fraction
    positions, init_diag = poisson_disk_place_rect(
        start_radii,
        box_lengths,
        rng,
        max_attempts_per_particle=int(args.max_attempts_per_particle),
        candidates_per_particle=int(args.candidates_per_particle),
        progress_every=int(args.progress_every),
    )

    mean_target_diameter = max(2.0 * float(np.mean(radii)), 1.0e-12)
    verlet_skin = float(args.verlet_skin)
    if verlet_skin <= 0.0:
        verlet_skin = float(args.verlet_skin_fraction) * mean_target_diameter
    if verlet_skin <= 0.0:
        raise ValueError("Verlet skin must be positive.")

    stage_diags = []
    max_overlap = 0.0
    overlap_count = 0
    for stage in range(1, int(args.stages) + 1):
        frac = stage / float(args.stages)
        stage_radii = start_radii + frac * (radii - start_radii)
        positions, diag = force_biased_relax_rect(
            positions,
            stage_radii,
            box_lengths,
            rng,
            max_iterations=int(args.max_iterations_per_stage),
            initial_outer_ratio=float(args.outer_diameter_ratio),
            contraction_rate=float(args.contraction_rate),
            force_scaling_factor=float(args.force_scaling_factor),
            max_displacement_fraction=float(args.max_displacement_fraction),
            tolerance_overlap=float(args.intermediate_tolerance_overlap),
            verlet_skin=verlet_skin,
        )
        max_overlap = float(diag["max_overlap"])
        overlap_count = int(diag["overlap_count"])
        stage_diags.append(
            {
                "stage": int(stage),
                "radius_fraction": float(initial_fraction + frac * (1.0 - initial_fraction)),
                **diag,
            }
        )
        print(
            "stage "
            f"{stage}/{args.stages}: max_overlap={max_overlap:.3e} um, "
            f"overlap_count={overlap_count}, stop={diag['stop_reason']}"
        )

    positions, final_diag = force_biased_relax_rect(
        positions,
        radii,
        box_lengths,
        rng,
        max_iterations=int(args.final_cleanup_steps),
        initial_outer_ratio=1.0,
        contraction_rate=float(args.contraction_rate),
        force_scaling_factor=float(args.force_scaling_factor),
        max_displacement_fraction=float(args.max_displacement_fraction),
        tolerance_overlap=float(args.tolerance_overlap),
        verlet_skin=verlet_skin,
    )
    max_overlap = float(final_diag["max_overlap"])
    overlap_count = int(final_diag["overlap_count"])
    status = "success" if max_overlap <= float(args.tolerance_overlap) else "warning"
    diagnostics = {
        "name": "force_biased_rectangular_periodic",
        "status": status,
        "elapsed_time_s": float(time.perf_counter() - start),
        "note": (
            "Rectangular-periodic adaptation of SpherePackGen's force_biased "
            "dense generator: reduced-radius placement, staged radius growth, outer-shell "
            "repulsive relaxation, and outer diameter ratio contraction."
        ),
        "box_lengths_um": box_lengths.tolist(),
        "initial_radius_fraction": float(initial_fraction),
        "initialization_diagnostics": init_diag,
        "stages": int(args.stages),
        "max_iterations_per_stage": int(args.max_iterations_per_stage),
        "final_cleanup_steps": int(args.final_cleanup_steps),
        "force_scaling_factor": float(args.force_scaling_factor),
        "outer_diameter_ratio_initial": float(args.outer_diameter_ratio),
        "nominal_density_ratio": float(NOMINAL_DENSITY_RATIO),
        "contraction_rate": float(args.contraction_rate),
        "max_displacement_fraction": float(args.max_displacement_fraction),
        "intermediate_tolerance_overlap_um": float(args.intermediate_tolerance_overlap),
        "final_tolerance_overlap_um": float(args.tolerance_overlap),
        "verlet_skin_um": float(verlet_skin),
        "final_max_overlap_estimate_um": float(max_overlap),
        "final_overlap_count_estimate": int(overlap_count),
        "final_cleanup": final_diag,
        "stage_diagnostics": stage_diags,
    }
    return np.mod(positions, box_lengths), diagnostics


def find_overlap_pairs_rect(
    positions: np.ndarray,
    radii: np.ndarray,
    box_lengths: np.ndarray,
    tolerance: float,
):
    if len(radii) < 2:
        return [], float("inf")
    max_radius = float(np.max(radii))
    cell_list = RectPeriodicCellList(box_lengths, cutoff=max(2.0 * max_radius, 1.0e-12))
    cell_list.build(positions)
    pairs = []
    min_gap = float("inf")
    for i, pos in enumerate(positions):
        for j in cell_list.nearby_indices(pos, radii[i] + max_radius):
            if j <= i:
                continue
            gap = pair_gap(pos, radii[i], positions[j], radii[j], box_lengths)
            min_gap = min(min_gap, gap)
            if gap < -tolerance:
                pairs.append((int(i), int(j), float(gap)))
    return pairs, min_gap


def validate_rect_packing(
    positions: np.ndarray,
    radii: np.ndarray,
    box_lengths: np.ndarray,
    species_id: np.ndarray,
    tolerance_overlap: float,
) -> ValidationReport:
    errors: list[str] = []
    warnings: list[str] = []
    out_of_bounds = int(np.sum((positions < -1.0e-12) | (positions >= box_lengths + 1.0e-12)))
    if out_of_bounds:
        errors.append(f"{out_of_bounds} coordinate values are outside the rectangular box.")
    overlap_pairs, min_gap = find_overlap_pairs_rect(positions, radii, box_lengths, tolerance_overlap)
    if overlap_pairs:
        errors.append(f"{len(overlap_pairs)} overlapping particle pairs exceed tolerance.")
    max_overlap = max(0.0, -float(min_gap)) if np.isfinite(min_gap) else 0.0
    unique_species, counts = np.unique(species_id, return_counts=True)
    metrics = {
        "n_particles": int(len(radii)),
        "box_lengths_um": [float(v) for v in box_lengths],
        "box_volume_um3": float(np.prod(box_lengths)),
        "packing_fraction_actual": packing_fraction(radii, box_lengths),
        "min_gap_um": float(min_gap),
        "max_overlap_um": float(max_overlap),
        "overlap_pair_count": int(len(overlap_pairs)),
        "out_of_bounds_value_count": int(out_of_bounds),
        "radius_min_um": float(np.min(radii)),
        "radius_max_um": float(np.max(radii)),
        "radius_mean_um": float(np.mean(radii)),
        "radius_cv": float(np.std(radii) / np.mean(radii)),
    }
    for species, count in zip(unique_species, counts):
        mask = species_id == species
        species_volume = float(np.sum(4.0 * np.pi * radii[mask] ** 3 / 3.0))
        metrics[f"species_{int(species)}_count"] = int(count)
        metrics[f"species_{int(species)}_volume_fraction"] = species_volume / float(np.prod(box_lengths))
    return ValidationReport(passed=not errors, errors=errors, warnings=warnings, metrics=metrics)


def mixing_profile(
    positions: np.ndarray,
    species_id: np.ndarray,
    box_lengths: np.ndarray,
    bins: int,
):
    if bins <= 0:
        return []
    edges = np.linspace(0.0, float(box_lengths[2]), bins + 1)
    profile = []
    for i in range(bins):
        if i == bins - 1:
            mask = (positions[:, 2] >= edges[i]) & (positions[:, 2] <= edges[i + 1])
        else:
            mask = (positions[:, 2] >= edges[i]) & (positions[:, 2] < edges[i + 1])
        total = int(np.count_nonzero(mask))
        count_150 = int(np.count_nonzero(mask & (species_id == 0)))
        count_200 = int(np.count_nonzero(mask & (species_id == 1)))
        profile.append(
            {
                "z_min_um": float(edges[i]),
                "z_max_um": float(edges[i + 1]),
                "total": total,
                "count_150nm": count_150,
                "count_200nm": count_200,
                "fraction_150nm": float(count_150 / total) if total else 0.0,
                "fraction_200nm": float(count_200 / total) if total else 0.0,
            }
        )
    return profile


def write_particles_csv(
    path: Path,
    positions: np.ndarray,
    radii: np.ndarray,
    species_id: np.ndarray,
    source_id: np.ndarray,
):
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "particle_id",
                "x",
                "y",
                "z",
                "radius",
                "diameter",
                "species_id",
                "source_structure_id",
                "material_id",
            ]
        )
        for i, (pos, radius) in enumerate(zip(positions, radii)):
            writer.writerow(
                [
                    i,
                    f"{pos[0]:.16g}",
                    f"{pos[1]:.16g}",
                    f"{pos[2]:.16g}",
                    f"{radius:.16g}",
                    f"{2.0 * radius:.16g}",
                    int(species_id[i]),
                    int(source_id[i]),
                    int(species_id[i]),
                ]
            )


def write_hdf5(path: Path, positions: np.ndarray, radii: np.ndarray, species_id: np.ndarray, source_id: np.ndarray, box_lengths):
    try:
        import h5py
    except Exception:
        return False
    with h5py.File(path, "w") as h5:
        h5.create_dataset("positions", data=positions)
        h5.create_dataset("radii", data=radii)
        h5.create_dataset("species_id", data=species_id)
        h5.create_dataset("source_structure_id", data=source_id)
        h5.attrs["coordinate_unit"] = "um"
        h5.attrs["box_lengths_um"] = np.asarray(box_lengths, dtype=float)
        h5.attrs["boundary"] = "periodic_rectangular"
    return True


def write_outputs(
    out_dir: Path,
    positions: np.ndarray,
    radii: np.ndarray,
    species_id: np.ndarray,
    source_id: np.ndarray,
    box_lengths: np.ndarray,
    diagnostics: dict,
    validation: ValidationReport,
    profile: list[dict],
    args: argparse.Namespace,
):
    out_dir.mkdir(parents=True, exist_ok=True)
    write_particles_csv(out_dir / "particles_real_units.csv", positions, radii, species_id, source_id)
    hdf5_written = write_hdf5(out_dir / "particles.h5", positions, radii, species_id, source_id, box_lengths)

    metadata = {
        "project": {
            "name": "mixed_150nm_200nm_3x3x6um_force_biased",
            "description": (
                "All particles imported from the 150 nm and 200 nm monodisperse structures, "
                "randomly mixed and re-packed in a 3 x 3 x 6 um periodic rectangular box."
            ),
        },
        "inputs": {
            "input_150nm_csv": str(args.input_150),
            "input_200nm_csv": str(args.input_200),
            "species_0": "150 nm particles from monodisperse_150nm_phi050_3um",
            "species_1": "200 nm particles from monodisperse_200nm_phi050_3um",
        },
        "box": {
            "box_lengths_um": box_lengths.tolist(),
            "boundary": "periodic_rectangular",
        },
        "generator": diagnostics,
        "validation": asdict(validation),
        "mixing_profile_z": profile,
        "outputs": {
            "particles_real_units_csv": "particles_real_units.csv",
            "particles_h5": "particles.h5" if hdf5_written else None,
            "metadata_json": "metadata.json",
            "validation_report_json": "validation_report.json",
            "mixing_profile_csv": "mixing_profile_z.csv",
        },
    }
    (out_dir / "metadata.json").write_text(json.dumps(_json_ready(metadata), indent=2), encoding="utf-8")
    (out_dir / "validation_report.json").write_text(
        json.dumps(_json_ready(asdict(validation)), indent=2),
        encoding="utf-8",
    )
    with (out_dir / "mixing_profile_z.csv").open("w", newline="", encoding="utf-8") as f:
        fieldnames = ["z_min_um", "z_max_um", "total", "count_150nm", "count_200nm", "fraction_150nm", "fraction_200nm"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in profile:
            writer.writerow(row)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Mix the generated 150 nm and 200 nm packings in a 3 x 3 x 6 um periodic box."
    )
    parser.add_argument("--input-150", type=Path, default=DEFAULT_INPUT_150)
    parser.add_argument("--input-200", type=Path, default=DEFAULT_INPUT_200)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--box", type=float, nargs=3, default=[3.0, 3.0, 6.0], metavar=("LX", "LY", "LZ"))
    parser.add_argument("--seed", type=int, default=20260630)
    parser.add_argument("--dry-run", action="store_true", help="Load inputs and print counts without packing.")
    parser.add_argument("--stages", type=int, default=24)
    parser.add_argument("--initial-radius-fraction", type=float, default=0.35)
    parser.add_argument("--max-iterations-per-stage", type=int, default=400)
    parser.add_argument("--final-cleanup-steps", type=int, default=800)
    parser.add_argument("--force-scaling-factor", type=float, default=0.5)
    parser.add_argument("--outer-diameter-ratio", type=float, default=DEFAULT_OUTER_DIAMETER_RATIO)
    parser.add_argument("--contraction-rate", type=float, default=1.0e-3)
    parser.add_argument("--max-displacement-fraction", type=float, default=0.35)
    parser.add_argument("--verlet-skin", type=float, default=0.0, help="Absolute skin in um; 0 uses --verlet-skin-fraction.")
    parser.add_argument("--verlet-skin-fraction", type=float, default=0.5)
    parser.add_argument("--max-attempts-per-particle", type=int, default=30000)
    parser.add_argument("--candidates-per-particle", type=int, default=30)
    parser.add_argument("--tolerance-overlap", type=float, default=1.0e-9)
    parser.add_argument("--intermediate-tolerance-overlap", type=float, default=1.0e-7)
    parser.add_argument("--mixing-bins", type=int, default=12)
    parser.add_argument("--progress-every", type=int, default=1000)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    box_lengths = np.asarray(args.box, dtype=float)
    if box_lengths.shape != (3,) or np.any(box_lengths <= 0.0):
        raise ValueError("--box must contain three positive lengths in um.")

    input_150 = load_real_unit_csv(args.input_150, species_id=0, source_id=0, source_name="150nm")
    input_200 = load_real_unit_csv(args.input_200, species_id=1, source_id=1, source_name="200nm")
    radii = np.concatenate([input_150.radii, input_200.radii])
    species_id = np.concatenate([input_150.species_id, input_200.species_id])
    source_id = np.concatenate([input_150.source_id, input_200.source_id])

    rng = np.random.default_rng(args.seed)
    perm = rng.permutation(len(radii))
    radii = radii[perm]
    species_id = species_id[perm]
    source_id = source_id[perm]

    phi = packing_fraction(radii, box_lengths)
    print(f"loaded particles: {len(radii)} total")
    print(f"species 0 / 150 nm: {int(np.count_nonzero(species_id == 0))}")
    print(f"species 1 / 200 nm: {int(np.count_nonzero(species_id == 1))}")
    print(f"box lengths: {box_lengths.tolist()} um")
    print(f"actual volume fraction from imported particles: {phi:.12g}")
    if args.dry_run:
        return 0

    positions, diagnostics = generate_force_biased_rect(radii, box_lengths, rng, args)
    validation = validate_rect_packing(positions, radii, box_lengths, species_id, float(args.tolerance_overlap))
    profile = mixing_profile(positions, species_id, box_lengths, int(args.mixing_bins))
    write_outputs(args.output, positions, radii, species_id, source_id, box_lengths, diagnostics, validation, profile, args)

    print(f"output: {args.output}")
    print(f"validation_passed: {validation.passed}")
    print(f"max_overlap_um: {validation.metrics['max_overlap_um']:.3e}")
    print(f"min_gap_um: {validation.metrics['min_gap_um']:.3e}")
    return 0 if validation.passed else 2


if __name__ == "__main__":
    raise SystemExit(main())
